# Site settings
author: Uriah Harston
title: Why I decided to become a Software Engineer? 
header-img: img/home-bg.png
email: uharston@gmail.com
copyright_name: Uriah Harston
description: > # this means to ignore newlines until "baseurl:"
  Maybe you should become one too!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  uharston

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
